package com.david.guidedjournal

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Prompt - Data model for a daily journal prompt question.
 *
 * This class represents a single prompt stored in the Room database.
 * Each prompt can be categorized, assigned to a time of day, and marked
 * as mandatory for the user's daily prompt rotation.
 *
 * @property id Auto-generated unique identifier for the prompt
 * @property text The prompt question shown to the user
 * @property category The topic category of this prompt
 * @property timeOfDay When this prompt is shown: Morning, Afternoon, or Night
 * @property isMandatory Whether this is one of the 10 required daily prompts
 */
@Entity(tableName = "prompts")
data class Prompt(
    // Unique ID automatically generated by Room for each prompt.
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    // The actual journal question displayed to the user.
    val text: String = "",

    // Groups the prompt into a category such as Gratitude, Growth, or Wellness.
    val category: String = "",

    // Determines which part of the day this prompt belongs to.
    // Expected values are "Morning", "Afternoon", or "Night".
    val timeOfDay: String = "",

    // Marks whether this prompt participates in the required daily prompt rotation.
    val isMandatory: Boolean = false
)